baseURL: "https://althaser.me/"
languageCode: en-us
build:
  writeStats: true
# https://www.markdownguide.org/tools/hugo/
# https://gohugo.io/getting-started/configuration-markup/#goldmark
markup:
  goldmark:
    renderer:
      unsafe: true
title: "althaser's website"
# Uncomment below to use aafu as hugo theme. See instructions in README.md
# theme: aafu
params:
  author: Pedro Beja
  description: althaser's website
  copyright: >-
    powered by [hugo](https://gohugo.io/)
  theme:
    mainTheme: dark
    showAttribute: true
    singlePage: false
  accordion:
    - item: about_me
    - item: links
      expand: true    # default - only the first `expand: true` will take effect
    # - item: skills
    #  panel_id: skill-panel
